apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollamaverse-py-backend
  namespace: aiops
  labels:
    app: ollamaverse-py-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollamaverse-py-backend
  template:
    metadata:
      labels:
        app: ollamaverse-py-backend
    spec:
      containers:
        - name: ollamaverse-py-backend
          image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-py-backend:3.8
          ports:
            - containerPort: 8000

          # readinessProbe:
          #   httpGet:
          #     path: /models
          #     port: 8000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /models
          #     port: 8000
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
