apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollamaverse-frontend
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollamaverse-frontend
  template:
    metadata:
      labels:
        app: ollamaverse-frontend
    spec:
      containers:
        - name: ollamaverse-frontend
          image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-frontend:3.5
          ports:
            - containerPort: 80




