apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-viewer
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-viewer
  template:
    metadata:
      labels:
        app: loadtest-viewer
    spec:
      serviceAccountName: loadtest-viewer-sa
      containers:
        - name: loadtest-viewer
          image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-loadtest-viewer:1.2
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "ap-south-1"
            - name: S3_BUCKET
              value: "aiops-loadtest-reports"
            - name: DATABASE_URL
              value: "mongodb+srv://ollamaverse:ollamaverse@cluster0.fisei.mongodb.net/ollamaverse"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: loadtest-viewer
  namespace: aiops
spec:
  selector:
    app: loadtest-viewer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
