apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-viewer
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-viewer
  template:
    metadata:
      labels:
        app: loadtest-viewer
    spec:
      serviceAccountName: loadtest-viewer-sa
      containers:
        - name: loadtest-viewer
          image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-loadtest-viewer:1.3
          ports:
            - containerPort: 8080
          env:
            # --- ConfigMap References ---
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: loadtest-viewer-config
                  key: aws_region
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: loadtest-viewer-config
                  key: s3_bucket
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: loadtest-viewer-config
                  key: app_port

            # --- Secret References ---
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: loadtest-viewer-secret
                  key: database_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: loadtest-viewer-secret
                  key: redis_url